//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string refreshToken {
            get {
                return ((string)(this["refreshToken"]));
            }
            set {
                this["refreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool separateTagBindings {
            get {
                return ((bool)(this["separateTagBindings"]));
            }
            set {
                this["separateTagBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genre;mood")]
        public string recordingTagBindings {
            get {
                return ((string)(this["recordingTagBindings"]));
            }
            set {
                this["recordingTagBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genres")]
        public string releaseTagBindings {
            get {
                return ((string)(this["releaseTagBindings"]));
            }
            set {
                this["releaseTagBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genres")]
        public string releaseGroupTagBindings {
            get {
                return ((string)(this["releaseGroupTagBindings"]));
            }
            set {
                this["releaseGroupTagBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("synthpop;synth-pop\r\nuplifting trance;melodic trance\r\nalt-pop;alternative pop")]
        public string findReplace {
            get {
                return ((string)(this["findReplace"]));
            }
            set {
                this["findReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tagSubmitIsDestructive {
            get {
                return ((bool)(this["tagSubmitIsDestructive"]));
            }
            set {
                this["tagSubmitIsDestructive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cachedUsername {
            get {
                return ((string)(this["cachedUsername"]));
            }
            set {
                this["cachedUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genre")]
        public string recordingGenreField {
            get {
                return ((string)(this["recordingGenreField"]));
            }
            set {
                this["recordingGenreField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keywords")]
        public string recordingTagField {
            get {
                return ((string)(this["recordingTagField"]));
            }
            set {
                this["recordingTagField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool separateGenres {
            get {
                return ((bool)(this["separateGenres"]));
            }
            set {
                this["separateGenres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genre")]
        public string releaseGenreField {
            get {
                return ((string)(this["releaseGenreField"]));
            }
            set {
                this["releaseGenreField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keywords")]
        public string releaseTagField {
            get {
                return ((string)(this["releaseTagField"]));
            }
            set {
                this["releaseTagField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("genre")]
        public string releaseGroupGenreField {
            get {
                return ((string)(this["releaseGroupGenreField"]));
            }
            set {
                this["releaseGroupGenreField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keywords")]
        public string releaseGroupTagField {
            get {
                return ((string)(this["releaseGroupTagField"]));
            }
            set {
                this["releaseGroupTagField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool separateFieldsByEntityType {
            get {
                return ((bool)(this["separateFieldsByEntityType"]));
            }
            set {
                this["separateFieldsByEntityType"] = value;
            }
        }
    }
}
